name: core
description: Core package for projects
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl:
  cupertino_icons:
  retrofit:
  shared_preferences:
  go_router:
  logger:
  flutter_bloc:
  fluttertoast:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
